// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6QS-LdKqn-nQng8m-CI7cvwF6NF9K60',
    appId: '1:1088029839796:web:24a40a7a187b51e8b0e2e1',
    messagingSenderId: '1088029839796',
    projectId: 'quickenlancer-e4dad',
    authDomain: 'quickenlancer-e4dad.firebaseapp.com',
    storageBucket: 'quickenlancer-e4dad.firebasestorage.app',
    measurementId: 'G-H0ZZJ6PZTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-mcFsH0KbfxM_Ij8VqwH3sTiSdnHbQ0w',
    appId: '1:1088029839796:android:e369cf19e73165dab0e2e1',
    messagingSenderId: '1088029839796',
    projectId: 'quickenlancer-e4dad',
    storageBucket: 'quickenlancer-e4dad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFl8iJADSyH7QS-KhXWyMvaOefjlIatiU',
    appId: '1:1088029839796:ios:2dde34b8ea12c6bfb0e2e1',
    messagingSenderId: '1088029839796',
    projectId: 'quickenlancer-e4dad',
    storageBucket: 'quickenlancer-e4dad.firebasestorage.app',
    iosBundleId: 'com.example.quickenlancerApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFl8iJADSyH7QS-KhXWyMvaOefjlIatiU',
    appId: '1:1088029839796:ios:2dde34b8ea12c6bfb0e2e1',
    messagingSenderId: '1088029839796',
    projectId: 'quickenlancer-e4dad',
    storageBucket: 'quickenlancer-e4dad.firebasestorage.app',
    iosBundleId: 'com.example.quickenlancerApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg6QS-LdKqn-nQng8m-CI7cvwF6NF9K60',
    appId: '1:1088029839796:web:384b26239ccec520b0e2e1',
    messagingSenderId: '1088029839796',
    projectId: 'quickenlancer-e4dad',
    authDomain: 'quickenlancer-e4dad.firebaseapp.com',
    storageBucket: 'quickenlancer-e4dad.firebasestorage.app',
    measurementId: 'G-2K3BQ4F9ZG',
  );
}
